ALTER TYPE "AssetType" ADD VALUE IF NOT EXISTS 'S3_COMPATIBLE_STORAGE';
ALTER TYPE "AssetType" ADD VALUE IF NOT EXISTS 'AZURE_BLOB_STORAGE';
ALTER TYPE "AssetType" ADD VALUE IF NOT EXISTS 'GOOGLE_CLOUD_STORAGE';
