import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  IsBoolean,
  IsOptional,
  IsString,
  IsUUID,
  MaxLength,
  MinLength,
} from 'class-validator';

export class CreateMcpTokenDto {
  @ApiProperty({
    description: 'Human-readable label for this MCP access token.',
    example: 'Cursor local agent',
  })
  @IsString()
  @MinLength(1)
  @MaxLength(120)
  name: string;
}

export class UpdateMcpTokenDto {
  @ApiPropertyOptional({
    description: 'Updated display name for the token.',
    example: 'Cursor staging workspace',
  })
  @IsOptional()
  @IsString()
  @MinLength(1)
  @MaxLength(120)
  name?: string;

  @ApiPropertyOptional({
    description:
      'When false, the token is revoked and can no longer authorize MCP requests.',
    example: false,
  })
  @IsOptional()
  @IsBoolean()
  isActive?: boolean;
}

export class McpTokenResponseDto {
  @ApiProperty({
    description: 'Stable public token identifier embedded in the token value.',
    example: '6c0ae0a4-2740-4c37-aa29-c9c69522e053',
  })
  @IsUUID()
  id: string;

  @ApiProperty({ example: 'Cursor local agent' })
  name: string;

  @ApiProperty({
    description: 'Masked token preview shown in settings after creation.',
    example: 'inmcp_6c0ae0a4...VC-TM',
  })
  tokenPreview: string;

  @ApiProperty({
    description: 'Whether the token can currently authorize MCP requests.',
    example: true,
  })
  isActive: boolean;

  @ApiPropertyOptional({
    description: 'Most recent successful authorization timestamp.',
  })
  lastUsedAt: Date | null;

  @ApiPropertyOptional({
    description: 'Revocation timestamp, if the token has been disabled.',
  })
  revokedAt: Date | null;

  @ApiProperty()
  createdAt: Date;

  @ApiProperty()
  updatedAt: Date;
}

export class McpTokenCreatedResponseDto extends McpTokenResponseDto {
  @ApiProperty({
    description:
      'Full plaintext bearer token returned once at creation time. It is never returned again.',
    example:
      'inmcp_6c0ae0a4-2740-4c37-aa29-c9c69522e053.qxMSu7K1aK0pgr1Z4vPqIYFJ3ijS2n2OQq8v3hVC-TM',
  })
  @IsString()
  plainTextToken: string;
}

export class McpCapabilityGroupDto {
  @ApiProperty({ example: 'sources' })
  id: string;

  @ApiProperty({ example: 'Sources' })
  title: string;

  @ApiProperty({
    example:
      'Create, validate, update, delete, and run ingestion sources from MCP.',
  })
  description: string;

  @ApiProperty({
    type: [String],
    example: [
      'search_sources',
      'get_source',
      'create_source',
      'update_source',
      'delete_source',
    ],
  })
  toolNames: string[];

  @ApiProperty({
    type: [String],
    example: [
      'Search and filter sources',
      'Validate source configs against JSON Schema',
      'Trigger connection tests and runs',
    ],
  })
  operations: string[];
}

export class McpPromptSummaryDto {
  @ApiProperty({ example: 'brainstorm_custom_detector' })
  name: string;

  @ApiProperty({ example: 'Brainstorm Custom Detector' })
  title: string;

  @ApiProperty({
    example:
      'Guide an MCP client to propose regex, classifier, or entity detector configs before training.',
  })
  description: string;
}

export class McpOverviewResponseDto {
  @ApiProperty({
    description: 'Relative MCP endpoint path exposed by the API server.',
    example: '/mcp',
  })
  endpointPath: string;

  @ApiProperty({
    description: 'Transport mode exposed by the endpoint.',
    example: 'Streamable HTTP (JSON response mode)',
  })
  transport: string;

  @ApiProperty({
    description: 'Authorization scheme expected by the MCP endpoint.',
    example: 'Bearer token',
  })
  authScheme: string;

  @ApiProperty({
    description: 'Static token prefix generated by the API.',
    example: 'inmcp',
  })
  tokenPrefix: string;

  @ApiProperty({
    description: 'Authorization header example for MCP clients.',
    example:
      'Authorization: Bearer inmcp_6c0ae0a4-2740-4c37-aa29-c9c69522e053.qxMSu7K1aK0pgr1Z4vPqIYFJ3ijS2n2OQq8v3hVC-TM',
  })
  authHeaderExample: string;

  @ApiProperty({
    type: [String],
    example: [
      'Generate one token per MCP client or workspace.',
      'Store tokens in a secret manager, not in plain text config files.',
      'Rotate by creating a replacement token, then revoke the old one.',
      'Tokens are hashed at rest and shown only once after creation.',
    ],
  })
  bestPractices: string[];

  @ApiProperty({ type: [McpCapabilityGroupDto] })
  capabilityGroups: McpCapabilityGroupDto[];

  @ApiProperty({ type: [McpPromptSummaryDto] })
  prompts: McpPromptSummaryDto[];
}
