-- AlterEnum
ALTER TYPE "DetectorType" ADD VALUE 'PROMPT_INJECTION';
ALTER TYPE "DetectorType" ADD VALUE 'PHISHING_URL';
ALTER TYPE "DetectorType" ADD VALUE 'SPAM';
ALTER TYPE "DetectorType" ADD VALUE 'LANGUAGE';
ALTER TYPE "DetectorType" ADD VALUE 'CODE_SECURITY';
ALTER TYPE "DetectorType" ADD VALUE 'PLAGIARISM';
ALTER TYPE "DetectorType" ADD VALUE 'IMAGE_VIOLENCE';
ALTER TYPE "DetectorType" ADD VALUE 'OCR_PII';
